Add arguments and keep passphrases

diff --git a/mkfeud b/mkfeud
--- a/mkfeud
+++ b/mkfeud
@@ -42,7 +42,6 @@
 # +-------------+--------------+-----------------------+---------------------------------------------+--------------+
 
 # TODO:
-# * Read encryption passphrases once and reuse across the script
 # * Rework verbose logs
 # * Validate given device is not mounted
 # * Validate given device has enough capacity for all the partitions
@@ -50,11 +49,6 @@
 #   * Unmount chroot directories
 #   * Deactivate LVM volumes
 #   * Close LUKS encrypted partitions
-# * Command line args to:
-#   * Define root partition size
-#   * Define swap partition size
-#   * Use swap partition size equal to RAM of current system (should this be the default behaviour instead?)
-#   * Define the name of the data partition
 # * Track what's been created to clean up if there's an error?
 # * Automate ubuntu install (debootstrap? ubiquity --automatic?)
 # * Require usb hardware key in addition to passphrase to open enrypted boot partition
@@ -62,14 +56,13 @@
 
 set -euo pipefail
 
-declare -r VERSION='0.4'
+declare -r VERSION='0.5'
 
-# Modify these values to change mkfeud's behaviour.
-declare -r ROOT_SIZE=512
-declare -r SWAP_SIZE=32
-declare -r DATA_PART="USB Data"
-
-declare -r VERBOSE=true
+# Exit codes. The values greater than 63, as well as 0, are
+# identical to the definitions in '/usr/include/sysexits.h'.
+declare -r EX_OK=0          # successful termination
+declare -r EX_MOUNTED=1     # device has mounted partitions
+declare -r EX_USAGE=64      # command line usage error
 
 # GPT partition type GUIDs.
 declare -r GRUB="21686148-6449-6E6F-744E-656564454649"
@@ -77,53 +70,148 @@ declare -r ESP="C12A7328-F81F-11D2-BA4B-00A0C93EC93B"
 declare -r LUKS="CA7D7CCB-63ED-4C53-861C-1742536059CC"
 declare -r DATA="EBD0A0A2-B9E5-4433-87C0-68B6B72699C7"
 
+usage() {
+  echo \
+"
+USAGE:
+  $0  [OPTION]... DEVICE
+
+  Make DEVICE bootable with encrypted boot and root partitions.
+
+OPTIONS:
+  -r, --root-size=SIZE              specify the root partition size in GiB
+  -s, --swap-size=SIZE              specify the swap partition size in GiB
+  -d, --data-partition-name=NAME    specify the name to set for the data partition
+  
+  -h, --help                        display this help
+      --version                     display version
+"
+}
+
 main () {
-    local -r dev="$1"
+    parse_args "$@"
 
-    local -r devp="$( get_partition_prefix $dev )"
-    local -r devm="$( get_partition_prefix ${dev##*/} )"
+    declare -gr PASS_BOOT=$( read_passphrase "${DEVP}3 (boot)" )
+    declare -gr PASS_ROOT=$( read_passphrase "${DEVP}4 (root)" )
 
+    setup_partitions
+    enable_grub_cryptodisk
+    configure_encrypted_boot
+}
+
+parse_args () {
+    # Default values.
+    declare -g ROOT_SIZE=512
+    declare -g SWAP_SIZE="$( get_ram_size )"
+    declare -g DATA_PART="USB Data"
+    declare -g VERBOSE=false
+
+    # Optional arguments.
+    args=$( getopt --name "$0" \
+                --options=+"r:s:d:vh" \
+                --longoptions="root-size:,swap-size:,data-partition-name:,verbose,help,version" \
+                -- "$@"
+    )
+
+    if [ $? -ne 0 ]; then
+        usage "$EX_USAGE"
+    fi
+
+    eval set -- "$args"
+
+    # Process the options
+    while true; do
+        case "$1" in
+            -r|--root-size)
+                ROOT_SIZE="$2"
+                shift 2;;
+            
+            -s|--swap-size)
+                SWAP_SIZE="$2"
+                shift 2;;
+
+            -d|--data-partition-name)
+                DATA_PART="$2"
+                shift 2;;
+
+            -v|--verbose)
+                VERBOSE=true
+                shift;;
+
+            -h|--help)
+                usage
+                exit;;
+            
+            --version)
+                echo "mkfeud v$VERSION"
+                exit "$EX_OK";;
+
+            --)
+                shift
+                break;;
+
+            *)
+                echo "Invalid option: $1"
+                usage
+                exit "$EX_USAGE";;
+        esac
+    done
+
+    # Positional arguments.
+    if [ -z "${1:-}" ] || ! [ -b "$1" ]; then
+        echo "First positional argument is missing or is not a block device!"
+        usage "$EX_USAGE"
+        exit
+    fi
+
+    declare -gr DEV="$1"
+
+    declare -gr DEVP="$( get_partition_prefix $DEV )"
+    declare -gr DEVM="$( get_partition_prefix ${DEV##*/} )"
+}
+
+setup_partitions () {
     # 1. Pre-installation steps
     # 1.1. Prepare partitions
     info "Setting up partitions..."
     
     local -r size4=$(( ROOT_SIZE + SWAP_SIZE ))
 
-    sgdisk --zap-all "$dev" > /dev/null
+    sgdisk --zap-all "$DEV" > /dev/null
 
-    sgdisk --new=1:0:+1M        --change-name=1:GRUB         --typecode=1:"$GRUB" "$dev" > /dev/null
-    sgdisk --new=2:0:+512M      --change-name=2:EFI-SP       --typecode=2:"$ESP"  "$dev" > /dev/null
-    sgdisk --new=3:0:+1711M     --change-name=3:BOOT         --typecode=3:"$LUKS" "$dev" > /dev/null
-    sgdisk --new=4:0:+"$size4"G --change-name=4:rootfs       --typecode=4:"$LUKS" "$dev" > /dev/null
-    sgdisk --new=5:0:0          --change-name=5:"$DATA_PART" --typecode=5:"$DATA" "$dev" > /dev/null
+    sgdisk --new=1:0:+1M        --change-name=1:GRUB         --typecode=1:"$GRUB" "$DEV" > /dev/null
+    sgdisk --new=2:0:+512M      --change-name=2:EFI-SP       --typecode=2:"$ESP"  "$DEV" > /dev/null
+    sgdisk --new=3:0:+1711M     --change-name=3:BOOT         --typecode=3:"$LUKS" "$DEV" > /dev/null
+    sgdisk --new=4:0:+"$size4"G --change-name=4:rootfs       --typecode=4:"$LUKS" "$DEV" > /dev/null
+    sgdisk --new=5:0:0          --change-name=5:"$DATA_PART" --typecode=5:"$DATA" "$DEV" > /dev/null
 
-    info "Partitions setup:\n$( sgdisk --print "$dev" )\n"
+    info "Partitions setup:\n$( sgdisk --print "$DEV" )\n"
 
     # 1.2. Setup encrypted partitions
     info "Setting up encryption..."
     
-    cryptsetup luksFormat --type=luks1 "${devp}3"
-    info "Partition ${devp}3 encryption setup."
+    echo -n "$PASS_BOOT" | cryptsetup luksFormat -q --type=luks1 "${DEVP}3"
+    info "Partition ${DEVP}3 encryption setup."
 
-    cryptsetup luksFormat "${devp}4"
-    info "Partition ${devp}4 encryption setup."
+    echo -n "$PASS_ROOT" | cryptsetup luksFormat -q "${DEVP}4"
+    info "Partition ${DEVP}4 encryption setup."
 
     # 1.3. Unlock encrypted partitions
-    info "Unlocking encrypted partitions (${devp}3 & ${devp}4)..."
+    info "Unlocking encrypted partitions (${DEVP}3 & ${DEVP}4)..."
     
-    local -r luks_root="${devm}4_crypt"
+    local -r luks_root="${DEVM}4_crypt"
 
-    cryptsetup open "${devp}3" LUKS_BOOT
-    info "Partition ${devp}3 unlocked."
+    echo -n "$PASS_BOOT" | cryptsetup open "${DEVP}3" LUKS_BOOT
+    info "Partition ${DEVP}3 unlocked."
     
-    cryptsetup open "${devp}4" "$luks_root"
-    info "Partition ${devp}4 unlocked."
+    echo -n "$PASS_ROOT" | cryptsetup open "${DEVP}4" "$luks_root"
+    info "Partition ${DEVP}4 unlocked."
 
     # 1.4. Format filesystems
     info "Formatting filesystems..."
     
-    mkfs.fat -F 32 -S "$(blockdev --getpbsz "$dev")" "${devp}2"  > /dev/null
-    mkntfs --fast --quiet --label "$DATA_PART" -p 0 -H 0 -S 0 "${devp}5"
+    mkfs.fat -F 32 -S "$(blockdev --getpbsz "$DEV")" "${DEVP}2"  > /dev/null
+    mkntfs --fast --quiet --label "$DATA_PART" -p 0 -H 0 -S 0 "${DEVP}5"
 
     mkfs.ext4 -q -L boot /dev/mapper/LUKS_BOOT
 
@@ -138,9 +226,11 @@ main () {
     lvcreate --name root   --extents 100%FREE   vgubuntu
 
     info "LVM setup."
+}
 
+enable_grub_cryptodisk () {
     # 2. Installation steps
-    waitforuser "Start installation and continue after completing all forms."
+    echo_yellow "Complete the manual installation steps..."
 
     # 2.1. Wait until installer creates grub configuration
     while [ ! -d /target/etc/default/grub.d ]; do
@@ -149,7 +239,9 @@ main () {
     
     # 2.2. Enable grub support for encrypted partitions
     echo "GRUB_ENABLE_CRYPTODISK=y" > /target/etc/default/grub.d/local.cfg
+}
 
+configure_encrypted_boot () {
     # 3. Post-installation steps
     waitforuser "Let installation finish and continue after selecting \"Continue Testing\"."
 
@@ -177,20 +269,37 @@ main () {
         chmod u=r,go-rwx /etc/luks/boot_os.keyfile
 
         # 3.5. Add key-file to LUKS volumes
-        echo -e '\e[0;32m[INFO] Adding key-file to ${devp}3 partition...\e[0m'
-        cryptsetup luksAddKey ${devp}3 /etc/luks/boot_os.keyfile
+        echo -e '\e[0;32m[INFO] Adding key-file to ${DEVP}3 partition...\e[0m'
+        echo -n \"$PASS_BOOT\" | cryptsetup luksAddKey \"${DEVP}3\" /etc/luks/boot_os.keyfile
 
-        echo -e '\e[0;32m[INFO] Adding key-file to ${devp}4 partition...\e[0m'
-        cryptsetup luksAddKey ${devp}4 /etc/luks/boot_os.keyfile
+        echo -e '\e[0;32m[INFO] Adding key-file to ${DEVP}4 partition...\e[0m'
+        echo -n \"$PASS_ROOT\" | cryptsetup luksAddKey \"${DEVP}4\" /etc/luks/boot_os.keyfile
 
         # 3.6. Add keys to the crypttab
-        echo 'LUKS_BOOT      UUID=$(blkid -s UUID -o value ${devp}3) /etc/luks/boot_os.keyfile luks,discard
-              ${devm}4_crypt UUID=$(blkid -s UUID -o value ${devp}4) /etc/luks/boot_os.keyfile luks,discard' \
+        echo 'LUKS_BOOT      UUID=$(blkid -s UUID -o value ${DEVP}3) /etc/luks/boot_os.keyfile luks,discard
+              ${DEVM}4_crypt UUID=$(blkid -s UUID -o value ${DEVP}4) /etc/luks/boot_os.keyfile luks,discard' \
             >> /etc/crypttab
 
         # 3.7. Update initramfs files
         update-initramfs -u -k all
     "
+}
+
+# Utilities.
+read_passphrase () {
+    local pass1 pass2
+
+    while true; do
+        read -rs -p "Enter $1 LUKS passphrase:" pass1; echo > /dev/tty
+        read -rs -p "Verify passphrase:"        pass2; echo > /dev/tty
+
+        if [ "$pass1" == "$pass2" ]; then
+            echo "$pass1"
+            return
+        fi
+
+        echo_red "Passphrases do not match!"
+    done
 }
 
 waitforuser () {
@@ -207,10 +316,17 @@ get_partition_prefix () {
     fi
 }
 
-info () {
-    if $VERBOSE; then
-        echo -e "\e[0;32m[INFO] $*\e[0m" > /dev/tty
-    fi
+get_ram_size() {
+  local -r size="$(awk '/MemTotal/ {print $2}' /proc/meminfo)"
+  echo "$(( size / (1024 * 1024) ))"
 }
 
+# Logging and echoing.
+echo_red    () { echo -e "\e[0;31m$*\e[0m" > /dev/tty; }
+echo_green  () { echo -e "\e[0;32m$*\e[0m" > /dev/tty; }
+echo_yellow () { echo -e "\e[0;33m$*\e[0m" > /dev/tty; }
+
+info () { [ $VERBOSE ] && echo_green "[INFO] $*"; }
+
+#
 main "$@"
